services:
  # FastApi
  api:
    volumes:
      - ../src:/package/src
    environment:
      - ENV_FILE=deploy/envs/.env.dev
      - REDIS_HOST=redis # Purely docker setup, since we use localhost in the pure local setup
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
      - "8080:8000"

  # PostgresSQL
  postgres:
    ports:
      - "5433:5432"

  # Test PostgresSQL
  test_postgres:
    image: postgres:16-alpine
    container_name: test_postgres_dba
    ports:
      - "5432:5432" # integration tests run in docker anyway
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${TEST_POSTGRES_USER} -d ${TEST_POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  # Redis
  redis:
    ports:
      - "6380:6379"