services:
  # FastApi
  api:
    build:
      dockerfile: deploy/Dockerfile-dev
    volumes:
      - ../:/package
      # Ensures there are no conflicts with .envs on local pc and the container
      - /package/.venv
    environment:
      - ENV_FILE=deploy/envs/.env.dev
      # For docker, we should use the internal port/host
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
      - "8080:8000"

  # PostgresSQL
  postgres:
    ports:
      - "5433:5432"

  # Redis
  redis:
    ports:
      - "6380:6379"