services:
  # FastApi
  api:
    environment:
      - ENV_FILE=deploy/envs/.env.prod
    ports:
      - "8000:8000"

  # PostgresSQL
  postgres:
    ports:
      - "5432:5432"

  # Redis
  redis:
    ports:
      - "6379:6379"